language: php

dist: precise

sudo: false

addons:
  apt:
    packages:
      - tidy

addons:
  firefox: "31.0"

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_ROOT_VERSION="4.0.x-dev"
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.0
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 7.1.2
      env: DB=MYSQL PDO=1 PHPUNIT_TEST=1
    - php: 7.0
      env: DB=MYSQL BEHAT_TEST=1
    - php: 7.0
      env: NPM_TEST=1

before_script:
# Init PHP
  - if [[ $PHPCS_TEST ]]; then pyrus install pear/PHP_CodeSniffer; fi
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer install --prefer-dist
  - composer require --prefer-dist --no-update symfony/config:^3.2 silverstripe/framework:4.0.x-dev silverstripe/siteconfig:4.0.x-dev silverstripe/config:1.0.x-dev silverstripe/admin:1.0.x-dev silverstripe/assets:1.0.x-dev silverstripe/versioned:1.0.x-dev
  - composer update

  - if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:2.0.x-dev --prefer-dist; fi
  - if [[ $DB == SQLITE ]]; then composer require silverstripe/sqlite3:2.0.x-dev --prefer-dist; fi

# Bootstrap cms / mysite folder
  - php ./tests/bootstrap/mysite.php

# Install NPM dependencies
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && yarn run build; fi

# Start behat services
  - if [[ $BEHAT_TEST ]]; then echo 'SS_BASE_URL=http://localhost:8080/' >> .env; fi
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/selenium-server-standalone > artifacts/selenium.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file tests/behat/serve-bootstrap.php &> artifacts/serve.log &); fi

script:
 - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests flush=1; fi
 - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @cms; fi
 - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
 - if [[ $NPM_TEST ]]; then git diff -w --no-color --relative=client; fi
 - if [[ $NPM_TEST ]]; then yarn run lint; fi
 - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi

after_failure:
  - if [[ $BEHAT_TEST ]]; then php ./framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/; fi
