language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

addons:
  firefox: "31.0"

env:
  global:
    - CORE_RELEASE=master
    - ARTIFACTS_REGION=us-east-1
    - ARTIFACTS_BUCKET=silverstripe-travis-artifacts
    - secure: "uql39x7U1QSn1PXeGCgkREOWt9avvedfNI/CF5ESeSnlpuLLKVmZcQ4V1kCO0/0K0WbBb9tMyC4we6KDccZFwhqPqmFD2q0m76CISz8eduEWoSU1HFfWzkGKfUbe1sVWZtr/zqLjrjrbXKxwnieK2HxXEw9nUmMLCUXvg9gShiQ="
    - secure: "0AL85od1+sMZ/cDyIcehVTGULy0n7IaYmVqJ2mDjbmcRkBx/LwTB9nWxcAgQmP0jt01N6Bjwy2vpBwmR0r0nOJYkUpHOv63F0qkhYVjjLRffwhw7nGbKW4HViTLfF0AfZaj3IErGsEWzpTbo0QOZvHI1OsWPTbQEIXyuZPV9nBk="

matrix:
  include:
    - php: 5.5
      env: DB=MYSQL
    - php: 5.5
      env: DB=PGSQL
    - php: 5.5
      env: DB=SQLITE
    - php: 5.6
      env: DB=MYSQL PDO=1
    - php: 5.6
      env: DB=MYSQL BEHAT_TEST=1
    - php: 7.0
      env: DB=MYSQL PDO=1

before_script:
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require 'silverstripe/behat-extension:~2.0-dev'; fi"
 - cd ~/builds/ss
 - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
 - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script:
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then vendor/bin/phpunit cms/tests; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat @cms; fi"

after_failure:
 - php ~/travis-support/travis_upload_artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging
