language: php 

php:
  - 5.4

addons:
  firefox: "31.0"

env:
  global:
    - "ARTIFACTS_AWS_REGION=ap-southeast-2"
    - "ARTIFACTS_S3_BUCKET=silverstripe-travis-artifacts"
    - secure: "TaDXopM96dMDv1Xga0pBD5QUkg5y68T+T/RQfP/Xc/kZxqItvXsRNBvLqVgbXYea0oxFh060Rbf7UpjbYnZpfJvoLcUwkk7R3VLuwhChWBAqB03TGwaSD7wyc23NJfdwIUQMADfaE9aOZhXB4N0OnfU3rwT5ZFrveqiGUKX6tiw="
    - secure: "D867nWrLverX+oDxvC+uE3GlMUkeJa+DWHmegqFIjyaF3PPVdKCgUqDvsubisNjLJBuHJOdBjh/Ov2t/YuhIIcEyVxpk/dqmuUdAaqtnpNKmclq8XwKlPnUOZFQqTJ+imiUNbYqcksDJA41Rb7nKXtn1mXMPub+h+ta1z6g/FLc="
  matrix:
    - DB=MYSQL CORE_RELEASE=3.1 BEHAT_TEST=1


before_script:
 - composer self-update
 - phpenv rehash
 - git clone git://github.com/mateusz/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require silverstripe/behat-extension:dev-develop
 - cd ~/builds/ss
 - php ~/travis-support/travis_setup_selenium.php --if-env BEHAT_TEST
 - php ~/travis-support/travis_setup_php54_webserver.php --if-env BEHAT_TEST

script: 
 - "if [ \"$BEHAT_TEST\" = \"\" ]; then vendor/bin/phpunit cms/tests; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat @cms; fi"

after_failure:
 - php ~/travis-support/travis_upload_artifacts.php --if-env BEHAT_TEST,ARTIFACTS_AWS_SECRET_ACCESS_KEY --target-path silverstripe/silverstripe-cms/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_S3_BUCKET/

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging
