language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

addons:
  firefox: "31.0"

env:
  global:
    - TRAVIS_NODE_VERSION="4"
    - CORE_RELEASE=4
    - COMPOSER_ROOT_VERSION="4.0.x-dev"

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1
    - php: 5.6
      env: DB=SQLITE PHPUNIT_TEST=1
    - php: 5.6
      env: DB=MYSQL PDO=1 PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 5.6
      env: DB=MYSQL BEHAT_TEST=1
    - php: 5.6
      env: NPM_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PDO=1 PHPUNIT_TEST=1

before_script:
 - "if [ \"$PHPCS_TEST\" = \"1\" ]; then pyrus install pear/PHP_CodeSniffer; fi"
 - phpenv rehash
 - phpenv config-rm xdebug.ini
 - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - composer install --prefer-dist
 - composer require silverstripe/framework:4.0.x-dev silverstripe/config:1.0.x-dev silverstripe/admin:1.0.x-dev silverstripe/assets:1.0.x-dev silverstripe/versioned:1.0.x-dev --prefer-dist
 - "if [ \"$DB\" = \"PGSQL\" ]; then composer require silverstripe/postgresql:2.0.x-dev --prefer-dist; fi"
 - "if [ \"$DB\" = \"SQLITE\" ]; then composer require silverstripe/sqlite3:2.0.x-dev --prefer-dist; fi"
 - "php ./tests/bootstrap/mysite.php"
 - "export DISPLAY=\":99\""
 - "export XVFBARGS=\":99 -ac -screen 0 1024x768x16\""
 - "if [ \"$NPM_TEST\" = \"1\" ]; then (nvm install $TRAVIS_NODE_VERSION && npm install --silent && npm run build); fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then sh -e /etc/init.d/xvfb start; sleep 3; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then (vendor/bin/selenium-server-standalone > selenium.log 2>&1 &); fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then (vendor/bin/serve --bootstrap-file tests/behat/serve-bootstrap.php &> serve.log &); fi"

script:
 - "if [ \"$PHPUNIT_TEST\" = \"1\" ]; then vendor/bin/phpunit tests flush=1; fi"
 - "if [ \"$BEHAT_TEST\" = \"1\" ]; then vendor/bin/behat .; fi"
 - "if [ \"$NPM_TEST\" = \"1\" ]; then git diff-files --quiet -w --relative=client; fi"
 - "if [ \"$NPM_TEST\" = \"1\" ]; then git diff -w --no-color --relative=client; fi"
 - "if [ \"$NPM_TEST\" = \"1\" ]; then (nvm use $TRAVIS_NODE_VERSION && npm run lint); fi"
 - "if [ \"$PHPCS_TEST\" = \"1\" ]; then composer run-script lint; fi"

after_success:
 - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then vendor/bin/phpunit tests flush=1 --coverage-clover=coverage.xml; fi"
 - "if [ \"$PHPUNIT_COVERAGE_TEST\" = \"1\" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi"

after_failure:
 - php ~/travis-support/travis_upload_artifacts.php --if-env BEHAT_TEST,ARTIFACTS_KEY --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/

branches:
  except:
    - 2.1
    - 2.2
    - 2.3
    - translation-staging
